language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade pylint
  - pip install --upgrade sphinx

install:
  - pip install -r requirements.txt

script:
  - python setup.py build
  - python setup.py install
  - make -C docs html
  - pytest -v
